### ISSUE TITLE
get_reward

### ISSUE THREAD

**Issue by Krsnadeva** [OctThe16th/PPO-Keras#1]
Hey OctThe16th!
I've been looking for a good implementation of the PPO in Keras (I am not very 'math notation' savvy, so it is hard for me to follow straight from the papers), I think you nailed it, but I failed to understand your call to:

    `136               r = self.get_reward(i, len(tmp_batch[0]))`

since _get_reward_ does not seem to be implemented. What am I missing?

I am trying a PPO to run in a real time environment of my own, not Gym. I already have other agents running (vanilla PG), but I could not figure out a way to compile the model, so I was using a K.function for training, and I think because of that my layer.get_weights() are returning empty. I do now, thanks to you! Cheers.

**Comment by LuEE-C** [comment]
Oops, you're right, just pushed a fix and a few changes, hope that helps!

**Comment by Krsnadeva** [comment]
Awesome Luis!
Thanks, will check it out.

Cheers and a great new year!
