### ISSUE TITLE
Tensorboardx Crashing the Code without Errors?

### ISSUE THREAD

**Issue by ghost** [OctThe16th/PPO-Keras#7]
I'd like to mention that i love your implementation, however i am experiencing an issue where the code just freezes/crashes without any error. No new epochs start and no errors are shown. I am not sure what is causing it, however i am suspecting it has something to do with Tensorboard, since the crashes usually occur during the flush time (120 seconds). Are you aware of such problems existing if not a solution?

**Comment by LuEE-C** [comment]
I am not seeing this problem on my end. The problem is most likely related to tensorboard and not the PPO code. I unfortunately can't help you with this, but the tensorboard part of the code can be safely removed without any adverse effect.

**Comment by ghost** [comment]
I solved it already, it was a bit of a silly question, thanks a lot of your answer though. Enjoying your implementation everyday so far!
